name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run specific tests - test_drone
      run: cargo test --test test_drone --verbose
    - name: Run specific tests - test_forwarding
      run: cargo test --test test_forwarding --verbose

    
