name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run specific tests - test_drone
      run: cargo test --test test_drone --verbose
    - name: Run specific tests - test_forwarding
      run: cargo test --test test_forwarding --verbose
    - name: Run specific tests - test_ack_nack
      run: cargo test --test test_ack_nack --verbose
    - name: Run specific tests - test_flooding
      run: cargo test --test test_flooding --verbose
    - name: Run specific tests - test_sc_command
      run: cargo test --test test_sc_command --verbose
    - name: Run specific tests - test_initialization
      run: cargo test --test test_initialization --verbose

    
